server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: reader
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数

  redis:
    host: redis # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

  rabbitmq:
    host: rabbit
    port: 5672
    virtual-host: /
    username: feng
    password: feng
    publisher-confirms: true #如果对异步消息需要回调必须设置为true

