spring:
  datasource:
    url: jdbc:mysql://localhost/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数

  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: es:9300

logging:
  path: /var/logs #配置日志生成路径
